// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YellowBook.API.Data;

#nullable disable

namespace YellowBook.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YellowBook.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 424, DateTimeKind.Utc).AddTicks(71),
                            Description = "Medical facilities and healthcare services",
                            Name = "Hospitals"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 424, DateTimeKind.Utc).AddTicks(830),
                            Description = "Accommodation and hospitality services",
                            Name = "Hotels"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 424, DateTimeKind.Utc).AddTicks(833),
                            Description = "Educational institutions",
                            Name = "Schools"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 424, DateTimeKind.Utc).AddTicks(835),
                            Description = "Internet and communication services",
                            Name = "Internet Providers"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 424, DateTimeKind.Utc).AddTicks(837),
                            Description = "Government offices and services",
                            Name = "Government Services"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 424, DateTimeKind.Utc).AddTicks(839),
                            Description = "Food and dining establishments",
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 424, DateTimeKind.Utc).AddTicks(841),
                            Description = "Various local business services",
                            Name = "Local Businesses"
                        });
                });

            modelBuilder.Entity("YellowBook.API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Mogadishu, Somalia",
                            CategoryId = 1,
                            CompanyName = "Mogadishu General Hospital",
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 426, DateTimeKind.Utc).AddTicks(1585),
                            Description = "Leading healthcare provider in Somalia",
                            Email = "info@mgh.som",
                            Logo = "",
                            PhoneNumber = "+252-1-123456",
                            Website = "https://mgh.som"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Downtown Mogadishu",
                            CategoryId = 2,
                            CompanyName = "Peace Hotel",
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 426, DateTimeKind.Utc).AddTicks(2683),
                            Description = "Luxury accommodation in the heart of Mogadishu",
                            Email = "reservations@peacehotel.som",
                            Logo = "",
                            PhoneNumber = "+252-1-234567",
                            Website = "https://peacehotel.som"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Airport Road, Mogadishu",
                            CategoryId = 3,
                            CompanyName = "Somali International School",
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 426, DateTimeKind.Utc).AddTicks(2686),
                            Description = "International education for Somali students",
                            Email = "admissions@sis.som",
                            Logo = "",
                            PhoneNumber = "+252-1-345678",
                            Website = "https://sis.som"
                        });
                });

            modelBuilder.Entity("YellowBook.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 3, 18, 45, 764, DateTimeKind.Utc).AddTicks(6614),
                            Email = "admin@yellowbook.som",
                            FullName = "System Administrator",
                            PasswordHash = "$2a$11$PIec4p/ZoZ4E8fmywwZ6Ret5Ys448IvfdpoynzFnwFPclYuZYXD3a",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("YellowBook.API.Models.Company", b =>
                {
                    b.HasOne("YellowBook.API.Models.Category", "Category")
                        .WithMany("Companies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YellowBook.API.Models.Category", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
